import{a as L,i,S as b}from"./assets/vendor-c145bea9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const v=document.querySelector(".form"),d=document.querySelector(".gallery"),y=document.querySelector(".loader"),c=document.querySelector(".load-more");let a={key:"41751590-b6ce5e955eace60263a904c25",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:40};function x(){y.style.display="block",d.style.display="none",c.style.display="none"}function p(){y.style.display="none",d.style.display="flex",c.style.display="block"}function w(o){return o.reduce((e,n)=>{const{largeImageURL:s,webformatURL:t,tags:r,likes:l,views:m,comments:f,downloads:h}=n;return e+`<li class="gallery-item">
        <a href=${s}> 
          <img class="gallery-img" src=${t} alt=${r} />
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${l}</span></p>
          <p>views: <span class="text-value">${m}</span></p>
          <p>comments: <span class="text-value">${f}</span></p>
          <p>downloads: <span class="text-value">${h}</span></p>
        </div>
      </li>`},"")}function P(o){const e=w(o);d.innerHTML+=e}function S(){new b(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}).refresh()}function u(){d.style.display="none",c.style.display="none",i.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"})}function H(){c.style.display="none",i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}async function g(o){x();try{const e=await L.get(`https://pixabay.com/api/?${o}`);p(),!e.data.totalHits||e.data.totalHits===0?u():(P(e.data.hits),S(),a.page++);const n=e.data.totalHits||0,s=a.page||1,t=a.per_page||20;n-s*t<=0&&H()}catch(e){console.error(e),e.response?i.error({position:"topRight",color:"red",message:`Server responded with an error: ${e.response.statusText}`}):e.request?i.error({position:"topRight",color:"red",message:"Network error. Please try again later."}):i.error({position:"topRight",color:"red",message:"An unexpected error occurred. Please try again later."}),p(),u()}}v.addEventListener("submit",o=>{o.preventDefault(),a.q=o.target.elements.search.value.trim(),a.page=1;const e=new URLSearchParams(a);g(e),o.currentTarget.reset()});c.addEventListener("click",o=>{o.preventDefault();const e=new URLSearchParams(a);g(e)});
//# sourceMappingURL=commonHelpers.js.map
