import{a as p,i,S as b}from"./assets/vendor-c145bea9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const v=document.querySelector(".form"),d=document.querySelector(".gallery"),g=document.querySelector(".loader"),c=document.querySelector(".load-more");let n={key:"41751590-b6ce5e955eace60263a904c25",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:40};function x(){g.style.display="block",d.style.display="none",c.style.display="none"}function u(){g.style.display="none",d.style.display="flex",c.style.display="block"}function w(o){return o.reduce((e,a)=>{const{largeImageURL:s,webformatURL:t,tags:r,likes:l,views:f,comments:h,downloads:L}=a;return e+`<li class="gallery-item">
        <a href=${s}> 
          <img class="gallery-img" src=${t} alt=${r} />
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${l}</span></p>
          <p>views: <span class="text-value">${f}</span></p>
          <p>comments: <span class="text-value">${h}</span></p>
          <p>downloads: <span class="text-value">${L}</span></p>
        </div>
      </li>`},"")}function P(o){const e=w(o);d.innerHTML+=e}function S(){new b(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}).refresh()}function y(){d.style.display="none",c.style.display="none",i.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"})}function H(){c.style.display="none",i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}async function m(o){x();try{const e=await p.get(`https://pixabay.com/api/?${o}`);u(),!e.data.totalHits||e.data.totalHits===0?y():(P(e.data.hits),S(),n.page++);const a=e.data.totalHits||0,s=n.page||1,t=n.per_page||20;a-s*t<=0&&H()}catch(e){if(console.error(e),p.isAxiosError(e)){const{response:a,request:s}=e;a?i.error({position:"topRight",color:"red",message:`Server responded with an error: ${a.statusText}`}):s&&i.error({position:"topRight",color:"red",message:"Network error. Please try again later."})}else i.error({position:"topRight",color:"red",message:"An unexpected error occurred. Please try again later."});u(),y()}}v.addEventListener("submit",o=>{o.preventDefault(),n.q=o.target.elements.search.value.trim(),n.page=1;const e=new URLSearchParams(n);m(e),o.currentTarget.reset()});c.addEventListener("click",o=>{o.preventDefault();const e=new URLSearchParams(n);m(e)});
//# sourceMappingURL=commonHelpers.js.map
